version: "2"

services:

    naxsi:
        image: jlabusch/docker-naxsi-proxy-waf
        links:
            - haproxy
        ports:
            - "8000:80"

    haproxy:
        image: dockercloud/haproxy:1.2.1
        links:
            - app
        expose:
            - "80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    app:
        image: docker-demo/app
        restart: always
        build: ./app
        links:
            - postgres
        expose:
            - "8000"
        environment:
            VIRTUAL_HOST: "shark.horse"

    postgres:
        image: postgres:9.4
        expose:
            - "5132"
        volumes:
            - ./db:/docker-entrypoint-initdb.d:ro

