version: "2"

services:

    haproxy:
        image: dockercloud/haproxy:1.2.1
        links:
            - app
        ports:
            - "8000:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    postgres:
        image: postgres:9.4
        expose:
            - "5132"
        volumes:
            - ./db:/docker-entrypoint-initdb.d:ro

    app:
        image: docker-demo/app
        build: ./app
        links:
            - postgres
        expose:
            - "8000"
        environment:
            VIRTUAL_HOST: "shark.horse"

